### DISCUSSION TITLE
How to stringify macros?

### DISCUSSION THREAD

**Discussion by ivan-pi** [fortran-lang/fpm#1110] [General]
I am porting a Make-based project to fpm, where the Makefile included

```
VERSION = 2.8.9

CC		?= cc
CFLAGS		?= -g -O2
CPPFLAGS	+= -DVERSION=\"$(VERSION)\"
```
Notice the quote characters around the VERSION macro.

In the fpm manifest I naively changed this to,

```toml
version = '2.8.9'

[preprocess]
[preprocess.cpp]
macros=["VERSION={version}"]
```

However the build breaks, with the error:

```
<command-line>: error: expected ',' or ';' before numeric constant
app/main.c:94:41: note: in expansion of macro 'VERSION'
   94 | static char ver[]="makedepf90 version " VERSION;
      |                                         ^~~~~~~
```

Does this mean I need to use [stringizing](https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html)?
