### DISCUSSION TITLE
Libraries requiring linking

### DISCUSSION THREAD

**Discussion by ivan-pi** [fortran-lang/fpm#326] [General]
I'm working an interface to the FLANN library for nearest neighbor searches: https://github.com/ivan-pi/fortran-flann/
I haven't put the manifest in yet, but was just wondering about the current status of build dependencies. Say my project must be linked to a system-installed FLANN library with the flag `-lflann`. If I put the code below in my manifest file,

```toml
[build]
link = ["flann"]
```

will the linkage dependency get propagated forward to any fpm project that uses my interface like shown below?

```toml
[dependencies]
fortran-flann = { git = "https://github.com/ivan-pi/fortran-flann" }
```

I've seen in Cargo that crates are able to communicate some meta-data for such cases, see [here](https://doc.rust-lang.org/cargo/reference/build-script-examples.html#using-another-sys-crate).
