### DISCUSSION TITLE
FPM + Lapack on GitHub Actions

### DISCUSSION THREAD

**Discussion by jacobwilliams** [fortran-lang/fpm#618] [General]
Does anybody have an example of using FPM with a project that requires LAPACK and have it working in GitHub Actions.

I've got: 

```yml
[[test]]
link = ["lapack"]
...
```

and that works fine locally. I guess I probably need to install Lapack... tried this in my CI config:

```
 sudo apt-get install -y libblas-dev liblapack-dev
```

But [didn't seem to work](https://github.com/jacobwilliams/nlesolver-fortran/runs/4279203247?check_suite_focus=true). Probably I'm missing something simple here. Does anyone have this working?

**Comment by awvwgk** [comment]
I'm using it quite extensively in quite a few of my projects like [dftd4](https://github.com/dftd4/dftd4) or [tblite](https://github.com/awvwgk/tblite). At least the Linux runners usually have a working BLAS/LAPACK installation around, for MacOS I usually install OpenBLAS from homebrew.

In the package manifest you need

```toml
link = ["lapack", "blas"]
```

**Reply by jacobwilliams** [reply]
Interesting...I do have that...but it isn't picking it up for some reason. Looking at your examples, I'm not sure how mine is different. (also using `ubuntu-latest`).

**Reply by awvwgk** [reply]
Looks like you are using LAPACK routines in the library source rather than just the test:

https://github.com/jacobwilliams/nlesolver-fortran/blob/50831bf7448822fa4a027c41184d8802c48c1508/src/nlesolver_module.f90#L624-L652

In this case the link dependency should go into the *build* table, rather than the *test* table.

**Comment by LKedward** [comment]
I ran into this issue when I tested this repository locally on Windows with openblas. I thought is was a quirk of Windows/openblas but I managed to fix it by moving the `link` entry to the `[build]` part of `fpm.toml` instead of under the individual `[[test]]`.
I think this is because the link flags get ordered differently with respect to the library depending on whether its in `[build]` or in `[[test]]`/`[[executable]]`.

```toml
name = "nlesolver-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2021, Jacob Williams"
license = "BSD-3"
description = "Nonlinear Equation Solver with Modern Fortran"
homepage = "https://github.com/jacobwilliams/nlesolver-fortran"
keywords = ["nle solver"]

[build]
auto-executables = false
auto-examples = false
auto-tests = false
link = "openblas"

[library]
source-dir = "src"

[install]
library = true

[[test]]
name = "nlesolver_test_1"
source-dir = "tests"
main = "nlesolver_test_1.f90"


```
