### DISCUSSION TITLE
Packaging NetCDF with fpm

### DISCUSSION THREAD

**Discussion by pgierz** [fortran-lang/fpm#699] [General]
Hi,

I really like the idea of fpm, and it seems to bring Fortran much more into the modern world. 

I mostly work with scientific numerical software, and a common data format there is NetCDF; so I am trying to get a fpm-friendly version of NetCDF prepared. Basically it is just writing the `fpm.toml` file. I've been reading through the documentation but I might need some guidance.

After a fork of the official NetCDF repo, I tried my hand at the very basics:
```toml
name = "NetCDF"
version = "4.5.4"
license = "GPL v3"                       # Probably wrong
author = "Unidata"
maintainer = "paul.gierz@awi.de"         # Only for the fpm version
copyright = "Copyright 2022, Paul Gierz" # Only for the fpm version
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = true
[library]
source-dir = "fortran"
```
Unfortunately, `fpm build` dies right away:
```
 Warning: Module netcdf in ./fortran/netcdf.f90 is a duplicate
<ERROR>*build_model*:Error: One or more duplicate module names found.
STOP 1
```

Probably I am just writing down the `fpm.toml` incorrectly, any help would be hugely appreciated!

All work so far can be found here: https://github.com/pgierz/netcdf-fortran 

Best,
Paul
