### ISSUE TITLE
Add ORCID identifier

### ISSUE THREAD

**Issue by RJaBi** [fortran-lang/fpm#1098]
### Motivation

What is ORCID?: "ORCID is a free, unique, persistent identifier (PID) for individuals to use as they engage in research, scholarship, and innovation activities."

Why add ORCID?: It's a persistent identifier which are preferable to non-persistant such as name, and email. Name & email may also be 'personal data' under GPDR (may).

What does an ORCID look like?: (Copied from Wikipedia)
ORCID IDs are a subset of the [International Standard Name Identifier](https://en.wikipedia.org/wiki/International_Standard_Name_Identifier) (ISNI).
Both ORCID and ISNI use 16-character identifiers, using the digits 0–9, and separated into groups of four by hyphens. The final character, which may also be a letter "X" representing the value "10".

In practice, the simplest solution is just to make the field available (as a string), and not enforce any checking.

### Specification

```toml
name = "fpm_test_exit_code"           
version = "0.1.0"                     
license = "license"                   
author = "Federico Perini"            
maintainer = "jane.doe@example.com"   
orcid = "0000-0000-0000-0000"         
copyright = "Copyright 2023, Jane Doe"
[build]                               
auto-executables = true               
[install]                             
library = false                       
````

### Prior Art

Existing art: The International Lattice Data Grid (https://hpc.desy.de/ildg/), a long running (started in 2002!) effort to share valuable (& expensive & large) lattice quantum chromodynamics data has recently updated it's XML schema saying ( https://www-zeuthen.desy.de/apewww/ILDG/specifications/MDWG-report-2.0.0-v1.pdf ):

> In previous QCDml versions, the <participant> in the <management> sub-tree had two mandatory
children, \<name> and \<institution> (with possibly empty values).
ORCID is meanwhile widely used in the scientific community as a unique, persistent. and public
identifier of a researchers. Also the fact that name and institution (i.e. the affiliation at the time of
the \<revisionAction>) are personal data is a concern with respect to GDPR which still requires
further consideration and clarification. Specification of the \<participant> by an ORCID is therefore
a desirable (and preferred) option, which has been requested (a-08) and may help to achieve GDPR
compliance.

This could be added in a similar fashion to i.e. Maintainer. I would not propose making it a default in `fpm new`

### Additional Information

This would be another field to be expanded upon in https://github.com/fortran-lang/fpm/issues/995 style.
