### ISSUE TITLE
Version from `git describe`

### ISSUE THREAD

**Issue by rzehumat** [fortran-lang/fpm#1115]
### Description

This is related to #1101 .
As stated in [the manifest](https://fpm.fortran-lang.org/spec/manifest.html#project-version), the project version is a number according to schematic versioning or file name. 

Would it be possible to add a possibility to obtain the project version from git, similarly to e.g. [setuptools-git-version](https://pypi.org/project/setuptools-git-version/) in Python? If possible, the version should be generated during compilation to keep information about when it was compiled.

My minimal idea is
**fpm.toml**
``` toml
name = "versiontest"
version = "$(git describe --always --tags --dirty)"
license = "license"
copyright = "Copyright 2025, rzehumat"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
[preprocess.cpp]
macros=["VERSION={version}"]
```

**app/main.f90**
``` fortran
program main
  implicit none

  print *, "Hello from main, version ", VERSION

end program main
```

Therefore, expected output of `fpm run` (or running the build binary) would be e.g.
```
Hello from main, version 0.1.0-1-g8fc1f32-dirty
```

### Possible Solution

I guess it would need to invoke `execute_command_line` or `run` (from `stdlib_system`) with the `git describe --always --tags --dirty` during `fpm build`, capture its output and then use it as `version` parameter. 

Since I am new to `fpm`, I can't estimate how feasible it would be.

### Additional Information

There exist packages for versions in Fortran, such as [Fortran-git-version](https://github.com/PlasmaFAIR/Fortran-git-version/tree/main) or [version-f](https://github.com/minhqdao/version-f). 
- The former can extract the version by `git describe`, but it seems to work only with `cmake` or `Make` (not `fpm`)
- The latter works with `fpm`, but it seems that it cannot get version from git during compilation.
- None of them affects the `version` parameter in `fpm.toml`

It would be possible to just use `execute_command_line` like
**app/main.f90**
``` fortran
program main
  implicit none

  print *, "Hello from main, version "
  call execute_command_line('git describe --always --tags --dirty' ) 

end program main
```
I don't like this solution since it's not compile-time -- i.e. if the program is compiled and binary is then copied outside the git repository, it will not yield any version.

Thanks in advance for any comments on this. Since I am new, I also apologize if I told anything incorrectly.
