### ISSUE TITLE
Package options in fpm.toml

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#191]
Came up in #190 and disabling/enabling the auto discovery features.

Generally, we need a way to customize fpm per package, as a first suggestion for the auto discovery:

```toml
[build]  # or config, ...
auto-executables = true
auto-tests = false
```

The fpm-options could include other information as well, like

```toml
[build]
fast-math = false  # don't use -ffast-math
standard = "2008"
preprocessor = "fypp"
```

There are two major questions here
1. Which table should hold options to customize fpm per package?
    - manifest root, `[build]`, `[config]`, ...
2. Which options do want to include in this section?
    - auto-discovery, standard, preprocessor, compiler flags, ...
