### ISSUE TITLE
Customizing fpm with plugins

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#211]
For commands like `fpm doc` or `fpm fmt` the available pool of tools is quite large and heterogeneous, if we want to support such functionality it must allow some kind of customization

A non-comprehensive list of tools for `fpm doc`:
- [doxygen](https://www.doxygen.nl/index.html)
  - requires `Doxyfile` as input
- [ford](https://github.com/Fortran-FOSS-Programmers/ford/wiki)
  - markdown file with yaml header as input, can have any name
- [ufpp](http://www.urbanjost.altervista.org/LIBRARY/libGPF/download/tmp/html/ufpp_overview.7.html)
  - actually a preprocessor which can also extract documentation

For `fpm fmt`:
- [lfortran fmt](https://gitlab.com/lfortran/lfortran)
  - actually an LLVM compiler + formatting
- [findent](https://sourceforge.net/projects/findent/)
  - can only take stdin and only writes to stdout
- [fprettify](https://github.com/pseewald/fprettify)
  - can recursively run over the source tree

All of those tools come with specific requirements and limitations. Also, I doubt there would be a perfect choice we could all agree on for those functionalities. One possibility is to collect all common tools and add native support for them in fpm, which might be cumbersome and if one has a personal set of tools for this task, they cannot use it with fpm in an automated way.

My proposal it to allow define those functions as “plugins” instead:

```toml
[plugin]
[plugin.fmt]  # Adds `fmt` command to fpm
program = "lfortran"
# Special variables like @INPUT@ and @OUTPUT@ are replaced by the filenames
command = ["fmt", "--no-color", "@INPUT@"]
# Standard input and standard output can be captured if necessary 
output.capture = true
# Probably needs a better way to define the interaction with the source...
scope = ["library/", "app/"]
```

Those could be defined locally in a `fpm.toml`, globally in a `.fpmrc.toml` or fetched like any other package. Note that installing the actual tool would be in many cases beyond the scope of fpm.
