### ISSUE TITLE
build-script location

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#249]
Currently the build-script can specified in the `[library]` table with:
```toml
library.build-script = "build.mk"
```
For an executable only project, a library table would still be required to select a build script, even if no library sources are actually available.

Adding the build-script to the `[build]` table feels more intuitive. Either as build-script or to reduce redundancy, just script:
```toml
build.build-script = "build.mk"
build.script = "build.mk"
```

*This might be a breaking change for some projects using this fpm feature.*

**Comment by ivan-pi** [comment]
In Cargo, the default behavior is to check for a file named `build.rs` in the root of the package. A custom build script can be specified as:
```
[package]
# ...
build = "custom_build_name.rs"
```
To disable automatic build script detection the setting is simply `build = false`. The possibility to use other build systems is then delegated to custom user packages which are called from `build.rs`.

The suggestion from @certik in #94 was to allow any kind of build script, be it a binary executable, shell script, Makefile, or other build system. Since fpm is only allowed to interact with the build script through environment variables and the output of the build script to standard output prepended with `fpm:` this seemed like a reasonable idea. However on further thought, I am worried this might become an obstacle for cross-compatibility between different operating systems. In this case fpm will need to report to the user to install CMake, Meson, Make, bash, etc. or whatever dependency. 

In any case, do we also want to support such automatic build script detection? 

Related to the immediate issue above, I agree that the `[library]` section does not feel right in case of executable-only projects. The `build.script` seems more fitting, also considering the fact the `link` keyword is in the same table.

**Comment by awvwgk** [comment]
I always wondered why Makefiles take such a special role in fpm, while CMake and meson are standardized enough to give a somewhat predictable behaviour for third-party tools, a Makefile can hide all kind of surprises and caveats inside (I never get tired of a random Makefile suddenly starting to write stuff in my home directory).

Interacting with other build files will always be difficult for fpm, have a look at https://github.com/fortran-lang/fortran-lang.org/issues/157 for an incomplete list. Preferably we can convince projects to switch to fpm, but most likely we will end up with projects supporting fpm and their original build system. My projects currently all support meson, but many have additional fpm support or CMake support, depending on the communities they find use in.

> In any case, do we also want to support such automatic build script detection?

Please don't, those features should be opt-in only, I don't want fpm to start auto-detecting my meson build files and force me to disable another of the automatic detection features in my projects.

**Comment by ivan-pi** [comment]
I certainly agree we don't want fpm interacting with other build systems aimed to be use independently from fpm. 

My proposition/question was only related to the way Cargo automatically looks for a `build.rs` file. Under this model behavior, `fpm` could look for `build.sh`, `build.mk`, `build.cmake`, etc.

But given that Fortran is not a monolithic/centralized language like Rust, and that there is such a variety of different build systems in use, it makes more sense to require package developers to specify a build script explicitly and save them the trouble of having to disable this manually. 

(I admit to having a soft spot for auto-detecting a `build.f90` program; the idea of writing a Fortran executable to specify a package build sounds both crazy and very fascinating at the same time.)

**Comment by awvwgk** [comment]
Okay, let's try to make the manifest syntax a bit more concrete.

I would propose we could have external build scripts (as array of strings), they are invoked by fpm and we just hope they play nicely together with fpm, but guarantee for nothing:

```toml
build.script = ["make", "-f", "build.mk"]  # or just ["build.mk"], make extension is detected
build.script = ["sh", "build.sh"]  # or just ["build.sh"], shell extension is detected
build.script = ["python", "build.py"]  # or just ["build.py"], Python extension is detected
build.script = ["ruby", "build.rb"] # or just ["build.rb"], Ruby extension is detected
build.script = ["cmake"]  # we might detect that it is CMake and run multiple steps for this script
```

And actual build scripts like proposed in #94 (provided as string), we will allow any format supported by fpm (f90, f, F90, F and c) as well as scripts (we can detect extensions as well and try to call the script with the correct program):

```toml
build.script = "build.f90"  # compile and run Fortran executable
build.script = "build.c"  # compile and run C executable
build.script = "build.sh"  # run shell script
build.script = "build.py"  # run Python script
build.script = "build.rb"  # run Ruby script
```

The script is expected to produce `fpm:` instructions which fpm parses and uses to build the project.

This might require a new table of `build-dependencies` at some point, which are usable in the build script.
