### ISSUE TITLE
Allow example as special executable type

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#275]
Suggested in https://github.com/fortran-lang/fpm/pull/257#pullrequestreview-546696582.

Additionally to the currently available `executable` and `test` tables an `example` table would allow to have usage example in a project which do not count as production executables but rather as demonstrations.

The syntax would be identical to the `executable` and `test` table with:

```toml
[[example]]
name = "demo"
source-dir = "example"  # suggestions for the default dir?
main = "main.f90"
```

Also, example executables can be automatically discovered like executables or test:

```toml
[build]
auto-examples = true
```
