### ISSUE TITLE
Create a dependency lock file

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#320]
The current dependency handler creates a cache in `build/cache.toml` which was intended as prototype for the lock file, for *fpm* the cache would look like:

```toml
[fpm]
version = "0.1.3"
proj-dir = "."
[toml-f]
version = "0.2.1"
proj-dir = "build/dependencies/toml-f"
git = "https://github.com/toml-f/toml-f"
obj = "2f5eaba864ff630ba0c3791126a3f811b6e437f3"
rev = "2f5eaba864ff630ba0c3791126a3f811b6e437f3"
[M_CLI2]
version = "0.1.0"
proj-dir = "build/dependencies/M_CLI2"
git = "https://github.com/urbanjost/M_CLI2.git"
obj = "e59fb2bfcf36199f1af506f937b3849180454a0f"
rev = "e59fb2bfcf36199f1af506f937b3849180454a0f"
```

Note that the git object in package manifest is currently used in *fpm* as alternative to a lock file. The information required for the lock file should boil down to the package name, its version and the git revision, which are already present in the dependency cache.

In principle, we have everything together to promote the dependency cache to a dependency lock (`fpm.lock`?).
