### ISSUE TITLE
Unexpected windows-gfortran version (8.1) in fpm/GitHub-CI(workflow:CI.yml)

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/fpm#537]
I don't know if this is a problem. 
As far as I know, `fortran-lang/stdlib` has removed support for `gcc` version (<=8).
`fpm/CI.yml` expected the `gcc` version under windows to be `9`, but actually got `8.1`.
You can see my [branch : check_gfortran_windows](https://github.com/fortran-fans/fpm/blob/a7a3fd44418801f4f6e1496a4661a74e308fdfe0/.github/workflows/CI.yml#L65~L69) and [screenshots](https://github.com/fortran-fans/fpm/runs/3276600784?check_suite_focus=true):
![image](https://user-images.githubusercontent.com/32035096/128656605-f63a7714-bdc6-479b-adaf-73ef3e9aaf56.png)

I don't know how to solve this problem, so I file an issue here.

**Comment by awvwgk** [comment]
Yes, this is an issue, we are using GCC/MinGW packaged by choco, which has a track record of packaging only very few GCC versions and updating only sporadically (measured in multiple of years). The alternative is using MSYS2, which always comes with a fairly recent version of GCC, but there are other issues (like https://github.com/fortran-lang/setup-fpm/issues/4, potential solution https://github.com/fortran-lang/fpm/issues/401). Another option is to download a standalone GCC/MinGW package from elsewhere (equation.com or winlibs.com).

I haven't yet spend much time to investigate Windows building beyond exploring MSYS2 and packaging fpm for the MinGW toolchain myself.

**Comment by awvwgk** [comment]
Here is how far I got with the GCC versions from https://github.com/brechtsanders/winlibs_mingw/releases. The workflow below will create a matrix for GCC 11, 10 and 9 and check whether the compilers have been added to the `PATH`. I didn't get it working with stdlib because `cmake` and `ninja` just didn't want to work together correctly for some reason, but might still be useful for fpm:

```yaml
jobs:
  gcc-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gcc_v: 11
            tag: 11.2.0-12.0.1-9.0.0-r1
            zip: winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip
          - gcc_v: 10
            tag: 10.3.0-12.0.0-9.0.0-r2
            zip: winlibs-x86_64-posix-seh-gcc-10.3.0-mingw-w64-9.0.0-r2.zip
          - gcc_v: 9
            tag: 9.4.0-9.0.0-r1
            zip: winlibs-x86_64-posix-seh-gcc-9.4.0-mingw-w64-9.0.0-r1.zip
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Download GCC/MinGW
      uses: i3h/download-release-asset@v1
      with:
        owner: brechtsanders
        repo: winlibs_mingw
        tag: ${{ matrix.tag }}
        file: ${{ matrix.zip }}

    - name: Setup GCC/MinGW
      run: |
        unzip ${{ matrix.zip }}
        echo "$PWD/mingw64/bin" >> $GITHUB_PATH

    - name: Check programs
      run: |
        echo $PATH
        gcc --version
        gfortran --version
```
