### ISSUE TITLE
Allow optional features in projects

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#609]
### Motivation

Not all parts of a project are always needed. Many Fortran projects can be build with and without MPI support for example. Currently there is no mechanism to express such features in the package manifest. An option is to rely on preprocessor and set reasonable default using constructs like shown below:

```c
#ifndef WITH_FEATURE
#define WITH_FEATURE 0
#endif
```

Since preprocessor might be the easiest way to express project local optional features, we could include such mechanism in fpm.

### Specification

A project could declare a *features* table and export this to the project via a preprocessor variable:

```toml
[features]
qp.preprocessor = "WITH_QP"
```

When used as a dependency the feature could be toggled using

```toml
[dependencies]
test-drive = {git = "https://github.com/fortran-lang/test-drive", features=["qp"]}
```

### Prior Art

Cargo has *features*: https://doc.rust-lang.org/cargo/reference/features.html

### Additional Information

A use case would be https://github.com/fortran-lang/test-drive/issues/7
The mechanism required is similar to the one described in https://github.com/fortran-lang/fpm/issues/577#issuecomment-926196637
