### ISSUE TITLE
Deciding Syntax for MACROS in manifest

### ISSUE THREAD

**Issue by arteevraina** [fortran-lang/fpm#721]
### Description

In fpm we currently have the syntax to define macros as a list in the manifest file that is fpm.toml. Something like : 

```
[preprocess]
[preprocess.cpp]
macros = ["FOO", "BAR"]
```
But, we also want that we can define `valued_marcos` as well in the manifest. In order, to do that we have to decide the syntax for the manifest for defined macros. 

### Possible Solution

The possible options for this can be:

### Option 1
```
[preprocess]
[preprocess.cpp]
macros = ["FOO", "BAR"]
[preprocess.cpp.valued_macros]
TESTMACRO1 = 4
TESTMACRO2 = 10
```
### Option 2
```
[preprocess]
[preprocess.cpp]
defined_macros = ["FOO", "BAR"]
valued_macros = {TESTMACRO1 = 4, TESTMACRO2 = 10}
```
## Option 3
```
[preprocess]
[preprocess.cpp]
macros = {FOO=5,  BAR=6, DEFINED_MACRO_FOO="somevalue"}
```

In option1 and option2, we will have two different ways of dealing with macros in manifest and this may not look clean. On the other hand, option3 looks clean but we will have to give some value to a Defined macro like `DEFINED_MACRO_FOO` which does not in actual needs to be equal to some value but needs to be defined in order for the program to work. 

I will also update this thread with more options in the coming days. But, I will require your feedback as well for this UI-based decision and proceed with the Pull Request for reading and setting macros.

### Additional Information

cc: @milancurcic @awvwgk @jvdp1

**Comment by everythingfunctional** [comment]
I lean towards option 2. Note that (I think) you'll have to deal with integer vs floating-point vs string values when adding the macros to the compile/pre-process command in different ways, due to the type-safe nature of Fortran. Shouldn't be too complicated, depending on how the TOML library we're using deals with that.

**Comment by awvwgk** [comment]
Another very serious downside in TOML is that [inline tables](https://toml.io/en/v1.0.0#inline-table) are not allowed to have line breaks, while inline arrays can span multiple lines, which allows for a more readable and diff-friendly package manifest.

My concern is more about accessing values from the manifest in the macro definitions to allow reusing some information from the manifest, like the version number:

```toml
[preprocess]
cpp.macros = [
  "PROJECT_VERSION=@version@",  # configure file like, meson uses this
  "PROJECT_VERSION={version}",  # Python and C++ formatter style
  "PROJECT_VERSION=<version>",  # Fortran string interpolation (non-standard extension) 
  # and so on...
]
```
