### ISSUE TITLE
Fortran feature table

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#722]
In light of supporting #577 and other related features which require to toggle “features” we should have a better mechanism than lumping things together in the *build* table.

An easy option would be to have a *features* table, with booleans

```toml
[features]
implicit-typing = true
```

However, we might need more than a binary system, so a feature which is either on, off or on some automatic value

```toml
[features]
implicit-typing = "enabled"  # options are "enabled", "disabled", "default" (compiler specific)
```

A more complex setup could be a *fortran* table, which also allows to select the standard (with *default* being what the compiler uses without options, *fpm* being our community standard and *f2018* the strict standard). Features could be instead of a subtable also an array of strings (easier to realize in a subtable than in the root table).

```toml
[fortran]
standard = "default"  # "fpm", "f2018", "f2008", ...
features = [
  "+implicit-typing",  # or "-implict-typing"
]
```
