### ISSUE TITLE
Allow accessing VCS revision for preprocessor macro

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#784]
Being able to access the current VCS revision in the manifest and pass it to the project as macro would be useful to identify exactly which revision was build or installed in a version printout

```toml
[preprocess.cpp]
macros = [
  "REVISION={revision}",
]
```

The big draw back of this approach however would be the change in the compiler options after every commit leading to a full rebuild.
