### ISSUE TITLE
Install dependencies from remote git URLs

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fpm#80]
As discussed in #33, let's allow installing fpm-enabled packages form their git repositories.

If the following is placed in fpm.toml:

```toml
[dependencies]
dependency_name = { git = git_url, tag = git_tag }
```

Then the package depends on `dependency_name`, which fpm will fetch from `git_url` and a specific git tag `git_tag`.

Here's a concrete example that will work, when this issue is implemented.

```toml
[dependencies]
datetime = { git = "https://github.com/wavebitscientific/datetime-fortran", tag = "v1.7.0" }
```

**Question**: If `tag` is omitted, should fpm fetch from the latest commit on master? I think so. Cargo [does it like that](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) as well. Then you could also do: 

```toml
[dependencies]
datetime = { git = "https://github.com/wavebitscientific/datetime-fortran" }
```
