### ISSUE TITLE
Use -standard-semanics by default with Intel compilers

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm#868]
Using this option would ensure that a more standard compliant mode is used with Intel compilers. Alternatively, this could be specified as an option in the Fortran table:

```toml
[fortran]
standard = "compiler-default"  # or "f2023", "f2018", ...
```

See also https://fortran-lang.discourse.group/t/5451/22
